version: "3.7"

services:
 dns:
  image: georgegeorgulasiv/dreamdns:latest
  deploy:
   replicas: 1
  secrets:
   - DREAMHOST_API_KEY
   - RECORD_TYPE
   - RECORD_TO_UPDATE
secrets:

 DOMAIN:
  external: true

 DREAMHOST_API_KEY:
  external: true

 RECORD_TYPE:
  external: true

 RECORD_TO_UPDATE:
  external: true
